development:
  adapter: postgresql
  encoding: unicode
  url: jdbc:postgresql://ubuntu-meindert/benchmark_development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  url: jdbc:postgresql://ubuntu-meindert/benchmark_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  url: jdbc:postgresql://ubuntu-meindert/benchmark_production
  username: postgres
  password: postgres
